emrulmax2/DataFuture

composer.lock, package.json, pnpm-lock.yaml
Package updated to latest version
=> packages updated

app/Http/Controllers/CoursCreationController.php
Qualification name on Course creation list Missing issue fixed. 
Order Desc done.
=> Course Creation Qualification

app/Http/Controllers/AdmissionController.php, app/Models/ReferralCode.php, resources/views/pages/students/live/show.blade.php
=> check update status change to live students

app/Jobs/ProcessStudentTaskDocument.php
This reverts commit 111b16282f56fb25fd28d44b0126083e92afcb93.
=> Revert "Update ProcessStudentTaskDocument.php"

app/Jobs/ProcessStudentTaskDocument.php
This reverts commit 6ab5d8a91562c9f65e853e4e01004f427c37a073.
=> Reapply "Update ProcessStudentTaskDocument.php"

resources/views/pages/students/live/show-menu.blade.php, resources/views/pages/tutor/module/view.blade.php
=> student terms link

app/Http/Controllers/Student/StudentController.php
This reverts commit 9006b64a72744c42db9489f469b039a06608ef3e.
=> Revert "Update StudentController.php"

resources/js/plan-tree.js, resources/js/plan.js, resources/views/pages/course-management/plan/index.blade.php, resources/views/pages/course-management/plan/tree/index.blade.php, resources/views/pages/tutor/module/view.blade.php
=> Plan Updates

vite.config.js
=> Please update the Vite

app/Http/Controllers/Personal_Tutor/DashboardController.php, app/Http/Controllers/Student/DatafutureController.php, resources/css/datafuture.css, resources/js/tutor-personal.js, resources/views/pages/personal-tutor/dashboard/index.blade.php, resources/views/pages/personal-tutor/dashboard/modals.blade.php, resources/views/pages/students/live/datafuture.blade.php, resources/views/pages/students/live/datafuture/session-years.blade.php, resources/views/pages/students/live/datafuture/student.blade.php
PT Dashboard & Student Datafuture
=> PT Dashboard & Student Datafuture

app/Http/Controllers/Personal_Tutor/DashboardController.php, app/Http/Requests/StudentQualificationRequest.php, app/Http/Requests/UpdateStudentQualificationRequest.php, app/Models/Plan.php, resources/views/pages/students/live/datafuture/modules.blade.php, resources/views/pages/students/live/show-modals.blade.php
Tutor Dashboard + Student Qualification Issue fixing
=> Tutor Dashboard + Student Qualification Issue fixing

app/Http/Controllers/CourseManagement/InstanceTermController.php, app/Http/Controllers/Student/DatafutureController.php, app/Models/CourseCreationInstance.php, resources/js/course-creation-instance.js, resources/views/pages/students/live/attendance/index.blade.php, resources/views/pages/students/live/datafuture/session-years.blade.php
Student Datafuture Modifications
=> Student Datafuture Modifications

app/Http/Requests/StudentQualificationRequest.php, app/Http/Requests/UpdateStudentQualificationRequest.php
Qualification Store & Update Request
=> Qualification Request

resources/js/student-edication-qualification.js
Update Student Education Qual JS
=> Update Student Education Qual JS

app/Http/Controllers/CourseManagement/PlanTreeController.php, app/Http/Requests/StudentAwardStoreRequest.php, resources/views/pages/students/live/datafuture/student.blade.php, resources/views/pages/students/live/result/index.blade.php
=> Plan Tree Issue Fixing

app/Http/Controllers/Agent/AgentManagementController.php, app/Models/Agent.php
=> Agent Modification

app/Http/Controllers/Agent/AgentManagementController.php, app/Models/AgentComission.php, app/Models/AgentComissionPayment.php, database/migrations/2025_02_04_084414_create_agent_comission_payments_table.php, database/migrations/2025_02_04_085212_add_agent_comission_payment_id_to_agent_comissions_table.php, database/migrations/2025_02_04_143200_alter_percentage_column_to_agent_comission_rules_table.php, resources/js/agent-management-payments.js, resources/js/agent-management-remittance.js, resources/views/pages/agent/management/index.blade.php, resources/views/pages/agent/management/payments.blade.php, resources/views/pages/agent/management/remittance.blade.php, routes/web.php, vite.config.js
=> Agent Comission Issue Fixing

app/Http/Controllers/Accounts/StorageController.php, app/Http/Controllers/AdmissionController.php, app/Http/Controllers/Agent/AgentManagementController.php, app/Http/Controllers/Student/UploadController.php, app/Models/AgentComission.php, app/Models/AgentComissionPayment.php, database/migrations/2025_02_05_112007_add_acc_transaction_id_to_agent_comission_payments_table.php, resources/js/admission-uploads.js, resources/js/agent-management-payments.js, resources/js/agent-management-remittance.js, resources/js/employee-upload.js, resources/js/student-upload.js, resources/views/pages/agent/management/payments.blade.php, resources/views/pages/agent/management/remittance.blade.php, resources/views/pages/employee/profile/documents.blade.php, resources/views/pages/students/admission/uploads.blade.php, resources/views/pages/students/live/uploads.blade.php
=> Agent Comission Payment

app/Http/Controllers/Accounts/StorageController.php
=> Storage Search Issue

app/Http/Controllers/Accounts/StorageController.php
=> Storage Controller Update

app/Http/Controllers/Accounts/AssetsRegisterController.php, app/Http/Controllers/Accounts/SummaryController.php
=> Assets Print Issue fixed

app/Http/Controllers/Personal_Tutor/DashboardController.php, app/Http/Controllers/Student/Frontend/DashboardController.php, resources/js/tutor-personal.js, resources/views/pages/personal-tutor/dashboard/index.blade.php, resources/views/pages/students/frontend/dashboard/index.blade.php, routes/web.php
Student Dashboard + Personal Tutor Dashboard
=> Student Dashboard + Personal Tutor Dashboard

resources/js/students.js, resources/views/pages/reports/data/index.blade.php
=> Student JS

app/Console/Commands/DailyClassReminder.php, app/Http/Controllers/HR/EmployeeTimeKeepingController.php, app/Models/Student.php
HR Time Keeping + Student Agreement Count
=> HR Time Keeping + Student Agreement Count

app/Http/Controllers/Accounts/StorageController.php, app/Http/Controllers/Agent/AgentManagementController.php, app/Models/AccTransaction.php, database/migrations/2025_02_13_091705_add_columns_has_payments_to_acc_transactions_table.php, resources/css/datafuture.css, resources/js/accounts-storage.js, resources/js/agent-management-payment-details.js, resources/js/agent-management-payments.js, resources/js/student-edication-qualification.js, resources/js/student-email.js, resources/js/student-employment-history.js, resources/js/student-global.js, resources/js/student-letter.js, resources/js/student-proof-id-check.js, resources/js/student-sms.js, resources/views/layout/components/top-bar.blade.php, resources/views/pages/agent/management/payments-details.blade.php, resources/views/pages/students/live/accounts.blade.php, resources/views/pages/students/live/communication.blade.php, resources/views/pages/students/live/course.blade.php, resources/views/pages/students/live/datafuture/course.blade.php, resources/views/pages/students/live/datafuture/qualification.blade.php, resources/views/pages/students/live/show-info.blade.php, resources/views/pages/students/live/show-menu.blade.php, resources/views/pages/students/live/show-modals.blade.php, resources/views/pages/students/live/show.blade.php, resources/views/pages/students/live/slc-history.blade.php, resources/views/pages/students/live/uploads.blade.php, routes/web.php, vite.config.js
=> Student Responsive Partial

app/Http/Controllers/AdmissionController.php, app/Http/Controllers/Student/StudentController.php, resources/js/admission-global.js, resources/views/pages/employee/profile/privilege.blade.php, resources/views/pages/students/admission/show-info.blade.php, resources/views/pages/students/frontend/dashboard/show-info.blade.php, routes/web.php
=> Text Issue Fixed

resources/css/datafuture.css, resources/views/layout/components/top-bar.blade.php, resources/views/pages/reports/accounts/index.blade.php, resources/views/pages/students/frontend/dashboard/index.blade.php, resources/views/pages/students/frontend/dashboard/module/view.blade.php, resources/views/pages/students/frontend/dashboard/profile/sidebar.blade.php
Student Portal Responsive + Accounts Report BTN issue fixed
=> Student Portal Responsive + Accounts Report BTN issue fixed

app/Http/Controllers/Personal_Tutor/AttendancePercentageController.php, app/Http/Controllers/Personal_Tutor/DashboardController.php, app/Http/Controllers/Programme/DashboardController.php, app/Http/Controllers/Staff/PendingTaskManagerController.php, resources/js/student-attendance-reports.js, resources/js/task-manager.js, resources/views/pages/programme/dashboard/tutors.blade.php, resources/views/pages/reports/attendance/index.blade.php, resources/views/pages/users/staffs/task/details.blade.php, routes/web.php
Task Filter + Tutor List Upgrading + Export
=> Task Filter + Tutor List Upgrading + Export

app/Http/Controllers/Programme/DashboardController.php, resources/js/programme-dashboard.js, resources/js/student-edication-qualification.js, resources/js/student-proof-id-check.js, resources/views/pages/programme/dashboard/index.blade.php, resources/views/pages/programme/dashboard/personal-tutors.blade.php, resources/views/pages/programme/dashboard/tutors-details.blade.php, resources/views/pages/programme/dashboard/tutors.blade.php, resources/views/pages/students/live/show-info.blade.php
=> Programm Dashboard Changes

app/Http/Controllers/Staff/DashboardController.php, resources/views/pages/students/live/show-info.blade.php
Info Blade Address line Breaks
=> Info Blade Address line Breaks

app/Http/Controllers/Student/ArchiveController.php
=> Student Archive Modified

app/Http/Controllers/Personal_Tutor/AttendancePercentageController.php, app/Http/Controllers/Personal_Tutor/DashboardController.php, app/Http/Controllers/Student/LetterController.php, app/Models/Plan.php, app/Traits/GenerateStudentLetterTrait.php, composer.lock, package-lock.json, resources/js/student-attendance-percentage.js, resources/views/pages/settings/letter/letter-tags.blade.php, routes/web.php
PT Dashboard Bellow Avg. Issue Fixed.
=> PT Dashboard Bellow Avg. Issue Fixed.

app/Http/Controllers/Personal_Tutor/AttendancePercentageController.php, app/Http/Controllers/Personal_Tutor/DashboardController.php
Student Attendance Bellow 60% Issue fixed.
=> Student Attendance Bellow 60% Issue fixed.

app/Http/Controllers/Student/LetterController.php, app/Traits/GenerateStudentLetterTrait.php, resources/js/student-email.js, resources/js/student-letter.js, resources/js/student-sms.js
Student Letter Result List Table Modifications
=> Student Letter Result List Table Modifications

app/Http/Controllers/Reports/SlcReports/SlcRecordReportController.php
=> SLC Record Report Update

app/Http/Controllers/HR/EmployeePortalController.php, app/Http/Controllers/Staff/DashboardController.php, app/Models/Employee.php, resources/js/hr-holiday-manager.js, resources/views/pages/employee/profile/holiday.blade.php
=> Employee Holiday Issue fixed.

app/Http/Controllers/Reports/Accounts/MarketingReportController.php, app/Http/Controllers/Reports/Accounts/SemesterComissionRateController.php, app/Http/Requests/MarketingReportGenerateRequest.php, app/Http/Requests/SemesterComissionRateStoreRequest.php, app/Models/SemesterComissionRate.php, database/migrations/2025_04_03_140101_create_semester_comission_rates_table.php, resources/css/datafuture.css, resources/js/marketing-reports.js, resources/views/pages/reports/accounts/index.blade.php, routes/web.php, vite.config.js
=> Accounts Marketing Report

app/Http/Controllers/Staff/PendingTaskManagerController.php, app/Http/Controllers/Student/StudentController.php, app/Mail/CommunicationSendMail.php, app/Models/StudentDocumentRequestForm.php, resources/js/student-global.js, resources/js/student-letter.js, resources/js/task-manager.js, resources/views/pages/students/frontend/dashboard/index.blade.php, resources/views/pages/students/live/accounts.blade.php, resources/views/pages/students/live/slc-history.blade.php, resources/views/pages/users/staffs/task/details.blade.php
Accounts Discounts & Status issue fixed.
=> Accounts Discounts & Status issue fixed.

resources/js/admission.js
=> Admission JS Issue Fixed

resources/js/admission-global.js, resources/views/pages/employee/profile/privilege.blade.php, resources/views/pages/settings/index.blade.php, resources/views/pages/students/admission/show-info.blade.php
Site Settings Permission & Applicant Rejected to In Progress
=> Site Settings Permission & Applicant Rejected to In Progress

app/Http/Controllers/Student/DatafutureController.php, app/Http/Controllers/Student/StudentController.php, app/Models/StudentContact.php, resources/views/pages/students/live/datafuture/student.blade.php, resources/views/pages/students/live/show-modals.blade.php
=> DF Issue fixing

app/Exports/StudyModeExport.php, app/Http/Controllers/Reports/DatafutureReportController.php, app/Http/Controllers/Settings/Studentoptions/StudyModeController.php, app/Http/Controllers/Student/DatafutureController.php, app/Http/Controllers/Student/PersonalDetailController.php, app/Http/Requests/StudyModesRequest.php, app/Imports/StudyModeImport, app/Models/StudentAttendanceTermStatus.php, resources/js/study-modes.js, resources/views/pages/settings/studentoption/index.blade.php, resources/views/pages/settings/studentoption/studymode/index.blade.php, resources/views/pages/students/live/datafuture/student.blade.php, routes/web.php, vite.config.js
DF Modification + Student Option Values
=> DF Modification + Student Option Values

app/Http/Controllers/Reports/DatafutureReportController.php, app/Http/Controllers/Student/StudentController.php, database/migrations/2025_07_16_094314_alter_qual_award_type_column_to_student_awards_table.php, database/migrations/2025_07_16_094604_alter_qual_award_type_column_to_student_attendance_term_statuses_table.php, resources/views/pages/students/live/datafuture/student.blade.php, resources/views/pages/students/live/show-info.blade.php
=> DF XML Modification

app/Exports/QualAwardResultExport.php, app/Http/Controllers/Reports/DatafutureReportController.php, app/Http/Controllers/Settings/Studentoptions/QualAwardResultController.php, app/Http/Controllers/Student/DatafutureController.php, app/Http/Requests/QualAwardResultRequest.php, app/Imports/QualAwardResultImport.php, app/Models/StudentCourseSessionDatafuture.php, database/migrations/2025_07_18_123318_add_invoice_hesa_id_column_to_student_stuload_information_table.php, database/migrations/2025_07_18_124719_add__rsnscsend_column_to_student_course_session_datafutures_table.php, resources/js/qual-award-results.js, resources/js/student-datafuture.js, resources/views/pages/settings/studentoption/index.blade.php, resources/views/pages/settings/studentoption/qualawardresult/index.blade.php, resources/views/pages/students/live/datafuture.blade.php, resources/views/pages/students/live/datafuture/student.blade.php, routes/web.php, vite.config.js
=> DF & Settings Issue fixed.

app/Http/Controllers/Reports/DatafutureReportController.php, app/Http/Controllers/Student/DatafutureController.php, resources/views/pages/students/live/datafuture/student.blade.php
=> YEARPREG Issue fixed.

app/Http/Controllers/Agent/AgentManagementController.php, app/Http/Controllers/Reports/DatafutureReportController.php, app/Models/AccTransaction.php, resources/js/agent-management-payments.js
=> Agent Commission Issue fixed.

app/Http/Controllers/Reports/DatafutureReportController.php
Update Datafuture Report Controller
=> Update Datafuture Report Controller

app/Http/Controllers/Budget/BudgetManagementController.php, resources/js/budget-management.js, resources/js/budget-requisition-show.js, resources/views/pages/budget/requisition/show.blade.php
Budget Requisition Modifications
=> Budget Requisition Modifications

app/Http/Controllers/Budget/BudgetManagementController.php, app/Models/BudgetRequisition.php, resources/js/budget-management.js, resources/views/pages/employee/profile/privilege.blade.php
Budget Management Modification
=> Budget Management Modification

app/Http/Controllers/Budget/BudgetManagementController.php, app/Http/Controllers/Reports/DatafutureReportController.php, app/Http/Controllers/Student/DatafutureController.php, app/Http/Requests/StudentUpdateStatusRequest.php, app/Models/Student.php, database/migrations/2025_08_15_142529_add_report_visibility_column_to_student_stuload_information_table.php, resources/js/student-datafuture.js, resources/views/pages/budget/requisition/show.blade.php, resources/views/pages/students/live/datafuture/student.blade.php, resources/views/pages/students/live/show-info.blade.php, routes/web.php
=> Datafuture + Status + Budget

app/Http/Controllers/CourseManagement/AssignController.php, app/Http/Controllers/Student/LetterController.php
Assign Issue + Letter Search Issue Fixed.
=> Assign Issue + Letter Search Issue Fixed.

app/Http/Controllers/Accounts/StorageController.php, app/Http/Controllers/Budget/BudgetManagementController.php, app/Models/AccTransaction.php, resources/js/accounts-storage.js
Storage Linked with Requisition
=> Storage Linked with Requisition

app/Http/Controllers/Student/SlcRegistrationController.php, resources/js/student-slc-registration.js
=> Slc History issue fixed.

resources/views/pages/students/live/slc-history.blade.php
=> Slc History Blade

resources/js/student-slc-registration.js, resources/views/pages/students/live/slc-history.blade.php
=> slc history update
